### ISSUE TITLE
questions

### ISSUE THREAD

**Issue by WertypasEstudios** [kr45732/skyblock-plus#362]
### Hi, I have a couple of questions:

1. **Create and add the bot to 90 servers with the name "Skyblock Plus - Emoji Server xx" (xx is the server number starting at 1)**

    Do I need to create 90 Discord servers? 

2. **Create 2 messages in a channel to be used for the scuffed event system (they will be constantly edited, so they must not be deleted). These messages update the assignment of messageId in...**

    - Do the messages need to be from me or from the bot?
    - Do these two messages need to say something specific?

**Comment by kr45732** [comment]
1. Yes – currently, there are 5,585 emojis (4,512 regular & 1,073 animated). Since each server can have 50 regular emojis and 50 animated emojis, and there are 4,512 regular emojis, you need at least 4,512/50 = ~91 servers. Note that you may need more as Hypixel adds more items to the game.
2. With the latest commit, you will no longer need to do this :)

**Comment by WertypasEstudios** [comment]
Ty <3
